/**
 * Unsubscribe routes — RFC 8058 compliant one-click unsubscribe.
 *
 * GET  /api/unsubscribe?email=…&tok=…
 *   → Validates the HMAC token, then renders a confirmation page with a
 *     <form method="POST"> button. Does NOT mutate the DB on GET — protects
 *     against corporate/Outlook/security link-prefetchers that follow every
 *     link in an email before the user sees it (silent opt-out risk).
 *
 * POST /api/unsubscribe?email=…&tok=…
 *   → Validates token, sets opted_out_at on members + registrations, returns
 *     success page. Handles both:
 *       a) Manual form submissions (from the GET confirmation page).
 *       b) RFC 8058 machine one-click posts from email clients (body =
 *          "List-Unsubscribe=One-Click", application/x-www-form-urlencoded).
 *
 * Token: HMAC-SHA256(SESSION_SECRET, "unsub:" + email.toLowerCase())
 * Generated by email.ts at send time; embedded in the List-Unsubscribe header
 * (for RFC 8058 clients) and the visible footer link (for manual clicks).
 */
import { Router, type IRouter } from "express";
import { createHmac, timingSafeEqual } from "crypto";
import { eq } from "drizzle-orm";
import { db, membersTable, registrationsTable } from "@workspace/db";

const router: IRouter = Router();

/**
 * Compute the HMAC-SHA256 unsubscribe token for a given email address.
 * Exported so tests can generate valid tokens without going through the API.
 */
export function makeUnsubToken(email: string): string {
  return createHmac("sha256", process.env.SESSION_SECRET ?? "")
    .update(`unsub:${email.toLowerCase()}`)
    .digest("hex");
}

// ── Shared page renderer ──────────────────────────────────────────────────────

function page(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>${title} — P3</title>
  <style>
    body{font-family:system-ui,sans-serif;background:#f8fafc;margin:0;min-height:100vh;
         display:flex;align-items:center;justify-content:center}
    .card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:40px;
          max-width:440px;width:100%;box-sizing:border-box;text-align:center;
          box-shadow:0 4px 24px rgba(0,0,0,.06)}
    .badge{display:inline-block;background:#f1f5f9;border-radius:8px;
           padding:8px 14px;font-size:13px;color:#64748b;margin-bottom:24px}
    h1{margin:0 0 12px;font-size:22px;color:#0f172a}
    p{margin:0 0 20px;color:#64748b;line-height:1.6;font-size:15px}
    a{color:#4169e1;text-decoration:none}
    .btn{display:inline-block;background:#ef4444;color:#fff;border:none;
         border-radius:10px;padding:12px 28px;font-size:15px;font-weight:700;
         cursor:pointer;text-decoration:none;margin-bottom:12px}
    .btn-ghost{background:#f1f5f9;color:#374151}
  </style>
</head>
<body>
  <div class="card">
    <div class="badge">P3 &middot; Padel Cubed</div>
    <h1>${title}</h1>
    ${body}
    <p style="margin-top:4px"><a href="https://www.padelcubed.co.uk">Back to P3</a></p>
  </div>
</body>
</html>`;
}

// ── Token validation helper ───────────────────────────────────────────────────

function validateToken(email: unknown, tok: unknown): boolean {
  if (!email || !tok || typeof email !== "string" || typeof tok !== "string") return false;
  const expected = makeUnsubToken(email);
  try {
    const expBuf = Buffer.from(expected, "hex");
    const tokBuf = Buffer.from(tok, "hex");
    return expBuf.length === tokBuf.length && timingSafeEqual(expBuf, tokBuf);
  } catch { return false; }
}

// ── GET — confirmation page (NO DB mutation) ──────────────────────────────────

router.get("/unsubscribe", (req, res): void => {
  const { email, tok } = req.query as { email?: string; tok?: string };

  if (!email || !tok || typeof email !== "string" || typeof tok !== "string") {
    res.status(400).send(page(
      "Invalid link",
      "<p>This unsubscribe link is missing required parameters. Please use the link from your email.</p>",
    ));
    return;
  }

  if (!validateToken(email, tok)) {
    res.status(400).send(page(
      "Invalid link",
      "<p>This unsubscribe link isn&#39;t valid. It may have been modified. Please use the original link from your email.</p>",
    ));
    return;
  }

  // Token valid — show the confirmation page. No DB mutation on GET.
  const action = `/api/unsubscribe?email=${encodeURIComponent(email)}&tok=${encodeURIComponent(tok)}`;

  res.status(200).send(page(
    "Confirm unsubscribe",
    `<p>Are you sure you want to stop receiving emails from P3 at <strong>${email}</strong>?</p>
     <form method="POST" action="${action}">
       <button type="submit" class="btn">Yes, unsubscribe me</button>
     </form>
     <p><a href="https://www.padelcubed.co.uk" class="btn btn-ghost">No, keep me on the list</a></p>`,
  ));
});

// ── POST — actual opt-out (RFC 8058 one-click + manual form) ─────────────────
//
// Accepts both:
//   a) application/x-www-form-urlencoded  { "List-Unsubscribe": "One-Click" }
//      — sent by RFC 8058-compliant email clients (Gmail, Apple Mail, …)
//   b) An empty POST body from the confirmation form above
//
// In both cases the email + tok come from the URL query string.

router.post("/unsubscribe", async (req, res): Promise<void> => {
  const { email, tok } = req.query as { email?: string; tok?: string };

  if (!email || !tok || typeof email !== "string" || typeof tok !== "string") {
    res.status(400).send(page(
      "Invalid link",
      "<p>This unsubscribe link is missing required parameters.</p>",
    ));
    return;
  }

  if (!validateToken(email, tok)) {
    res.status(400).send(page(
      "Invalid link",
      "<p>This unsubscribe link isn&#39;t valid. Please use the original link from your email.</p>",
    ));
    return;
  }

  const now = new Date();
  const lowerEmail = email.toLowerCase();

  try {
    // Set opted_out_at on member account if one exists
    await db
      .update(membersTable)
      .set({ optedOutAt: now })
      .where(eq(membersTable.email, lowerEmail));

    // Set opted_out_at on registration record if one exists
    await db
      .update(registrationsTable)
      .set({ optedOutAt: now })
      .where(eq(registrationsTable.email, lowerEmail));

    res.status(200).send(page(
      "You&#39;ve been unsubscribed",
      `<p>We&#39;ve removed <strong>${email}</strong> from our mailing list. You won&#39;t receive any further emails from P3.</p>
       <p>Changed your mind? <a href="https://www.padelcubed.co.uk">Re-register at padelcubed.co.uk</a>.</p>`,
    ));
  } catch (err) {
    console.error("[unsubscribe]", err);
    res.status(500).send(page(
      "Something went wrong",
      "<p>We couldn&#39;t process your request right now. Please reply to the email you received and we&#39;ll sort it manually.</p>",
    ));
  }
});

export default router;
