// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/padel-logos/ArcMotion.tsx": () => import("../components/mockups/padel-logos/ArcMotion.tsx"),
  "./components/mockups/padel-logos/BoldModern.tsx": () => import("../components/mockups/padel-logos/BoldModern.tsx"),
  "./components/mockups/padel-logos/CourtMark.tsx": () => import("../components/mockups/padel-logos/CourtMark.tsx"),
  "./components/mockups/padel-logos/ExchangeCross.tsx": () => import("../components/mockups/padel-logos/ExchangeCross.tsx"),
  "./components/mockups/padel-logos/MonogramBadge.tsx": () => import("../components/mockups/padel-logos/MonogramBadge.tsx")
};
